/**
 * NovaBlock — unified AI suggestion component
 *
 * Used across all 8D step screens and the CAPA intake wizard.
 * Wraps one Nova-generated suggestion with confidence indicator,
 * collapsible reasoning, and accept / discuss flow.
 *
 * States: idle → editing → accepted
 */

import { useEffect, useRef, useState } from "react";
import { ChevronDown, ChevronUp, MessageSquareText, Sparkles } from "lucide-react";
import { useAuditTrailStore, useUIStore } from "@/store";
import { cn } from "@/lib/utils";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface NovaBlockProps {
  /** The main suggestion text generated by Nova */
  suggestion: string;
  /** Optional chain-of-thought shown in the expandable reasoning panel */
  reasoning?: string;
  /** 0–100 confidence score displayed as a badge — hidden when omitted */
  confidence?: number;
  /** Called when user accepts (as-is or after editing). Receives final text. */
  onAccept?: (content: string) => void;
  /** When true, renders an animated skeleton while Nova is generating */
  loading?: boolean;
  /** Short qualifier appended to the header — e.g. "for Why 1" */
  context?: string;
  /** CAPA ID used for audit trail events */
  capaId?: string;
  /** Unique ID for this suggestion used in audit entries */
  suggestionId?: string;
}

type BlockState = "idle" | "editing" | "accepted";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Clamp confidence to 0–100, format as percentage string */
function formatConfidence(n: number): string {
  return `${Math.max(0, Math.min(100, Math.round(n)))}% confident`;
}

/** Color-tint the confidence badge based on score */
function confidenceClass(n: number): string {
  if (n >= 85) return "text-success";
  if (n >= 65) return "text-warning";
  return "text-destructive";
}

// ─────────────────────────────────────────────────────────────────────────────
// Skeleton (loading state)
// ─────────────────────────────────────────────────────────────────────────────

function NovaBlockSkeleton() {
  return (
    <div className="rounded-[var(--r-md)] border border-[var(--accent-line)] border-l-[3px] border-l-primary bg-elevated p-4">
      {/* Header placeholder */}
      <div className="mb-4 flex items-center gap-2">
        <div className="h-3.5 w-3.5 rounded-full animate-shimmer" />
        <div className="h-3.5 w-[120px] rounded-[var(--r-sm)] animate-shimmer" />
        <div className="ml-auto h-5 w-20 rounded-full animate-shimmer" />
      </div>

      {/* Body placeholders */}
      <div className="mb-2 h-3.5 w-full rounded-[var(--r-sm)] animate-shimmer" />
      <div className="mb-2 h-3.5 w-[88%] rounded-[var(--r-sm)] animate-shimmer" />
      <div className="mb-4 h-3.5 w-[72%] rounded-[var(--r-sm)] animate-shimmer" />

      {/* Action row placeholders */}
      <div className="flex gap-2">
        <div className="h-[30px] w-[130px] rounded-[var(--r-sm)] animate-shimmer" />
        <div className="h-[30px] w-[90px] rounded-[var(--r-sm)] animate-shimmer" />
        <div className="h-[30px] w-[50px] rounded-[var(--r-sm)] animate-shimmer" />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────

export function NovaBlock({
  suggestion,
  reasoning,
  confidence,
  onAccept,
  loading = false,
  context,
  capaId,
  suggestionId = "nova-block",
}: NovaBlockProps) {
  const [state, setState] = useState<BlockState>("idle");
  const [draft, setDraft] = useState(suggestion);
  const [showReasoning, setShowReasoning] = useState(false);
  const [isFlashing, setIsFlashing] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const addEvent = useAuditTrailStore((s) => s.addEvent);
  const openNovaChat = useUIStore((s) => s.openNovaChat);

  // Keep draft in sync if suggestion prop changes (e.g. Nova re-generates)
  useEffect(() => {
    if (state === "idle") setDraft(suggestion);
  }, [suggestion, state]);

  // ── Audit helper ───────────────────────────────────────────────────────
  function logAudit(eventType: "nova_suggestion_accepted" | "nova_suggestion_replaced", action: string) {
    if (!capaId) return;
    addEvent({
      actorName: "Nova Demo User",
      actorRole: "CAPA User",
      domain: "ai_decision",
      eventType,
      action,
      capaId,
      novaMetadata: {
        modelName: "Nova Mock Engine",
        modelVersion: "nova-demo-v1",
        confidenceScore: confidence ?? 84,
      },
    });
  }

  // ── Handlers ───────────────────────────────────────────────────────────
  function handleAccept() {
    // Flash the suggestion body before collapsing
    setIsFlashing(true);
    setTimeout(() => {
      setIsFlashing(false);
      setState("accepted");
      onAccept?.(draft);
      logAudit("nova_suggestion_accepted", `Nova suggestion "${suggestionId}" accepted.`);
    }, 380);
  }

  function handleApplyEdit() {
    setState("accepted");
    onAccept?.(draft);
    logAudit("nova_suggestion_accepted", `Nova suggestion "${suggestionId}" accepted after editing.`);
  }

  function handleCancelEdit() {
    setState("idle");
    setDraft(suggestion);
  }

  function handleDiscussWithNova() {
    const label = context ?? "Nova suggestion";
    openNovaChat({
      capaId,
      step: suggestionId,
      source: "nova-suggestion",
      suggestionId,
      suggestionContext: label,
      suggestionText: draft,
      initialDraft: `Help me review this ${label}. What should I ask or improve before using it?`,
    });
    logAudit("nova_suggestion_replaced", `Nova suggestion "${suggestionId}" opened in Ask Nova for discussion.`);
  }

  function handleRestore() {
    setState("idle");
    setDraft(suggestion);
  }

  // ── Loading skeleton ───────────────────────────────────────────────────
  if (loading) return <NovaBlockSkeleton />;

  // ── Accepted ───────────────────────────────────────────────────────────
  if (state === "accepted") {
    return (
      <div className="flex animate-[leadReveal_var(--dur-tab)_var(--ease-out)_both] flex-col items-start gap-2 rounded-[var(--r-md)] border border-[var(--accent-line)] bg-[var(--accent-soft)] px-3.5 py-[9px]">
        <div className="flex w-full items-center gap-2">
          <Sparkles
            size={13}
            strokeWidth={1.75}
            className="shrink-0 text-primary"
          />
          <span className="font-sans text-[13px] font-semibold text-primary">
            Nova suggestion applied
          </span>
          <span className="font-sans text-xs text-foreground-tertiary">
            — edit the field below to refine
          </span>
          <button
            onClick={handleRestore}
            className="ml-auto cursor-pointer border-0 bg-transparent px-1.5 py-0.5 font-sans text-xs leading-none text-foreground-tertiary"
          >
            Undo
          </button>
        </div>
        <p className="m-0 font-sans text-[13px] leading-[1.6] text-foreground-secondary">
          {draft}
        </p>
      </div>
    );
  }

  // ── Idle / Editing ─────────────────────────────────────────────────────
  return (
    <div className="animate-[leadReveal_var(--dur-reveal)_var(--ease-out)_both] overflow-hidden rounded-[var(--r-md)] border border-[var(--accent-line)] border-l-[3px] border-l-primary bg-elevated">
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div className="flex items-center gap-2 px-4 pt-3">
        <Sparkles
          size={15}
          strokeWidth={1.75}
          className="shrink-0 text-primary"
        />

        <span className="font-sans text-[13px] font-semibold leading-none text-foreground">
          Nova's suggestion
          {context && (
            <span className="ml-1.5 font-normal text-foreground-tertiary">
              {context}
            </span>
          )}
        </span>

        {/* Confidence badge */}
        {confidence !== undefined && (
          <span className={cn("ml-auto inline-flex items-center gap-1 whitespace-nowrap rounded-full border border-[var(--accent-line)] bg-[var(--accent-soft)] px-[9px] py-[3px] font-sans text-[11px] font-semibold tracking-[0.02em]", confidenceClass(confidence))}>
            {formatConfidence(confidence)}
          </span>
        )}
      </div>

      {/* ── Suggestion body ──────────────────────────────────────────────── */}
      <div
        className={cn(
          "mx-1 rounded px-4 pt-2.5 transition-[background] [transition-duration:380ms]",
          isFlashing ? "bg-[var(--accent-soft)]" : "bg-transparent",
        )}
      >
        {state === "editing" ? (
          <textarea
            ref={textareaRef}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            rows={4}
            className="box-border block w-full resize-y rounded-[var(--r-sm)] border border-primary bg-[var(--field-bg)] px-3 py-2.5 font-sans text-sm leading-[1.6] text-foreground outline-none shadow-[0_0_0_3px_var(--accent-soft)]"
          />
        ) : (
          <p className="m-0 font-sans text-[15px] leading-[1.6] text-foreground-secondary">
            {draft}
          </p>
        )}
      </div>

      {/* ── Expandable reasoning ─────────────────────────────────────────── */}
      {reasoning && state !== "editing" && (
        <div className="px-4 pt-2">
          <button
            onClick={() => setShowReasoning((v) => !v)}
            className="inline-flex cursor-pointer items-center gap-1 border-0 bg-transparent p-0 font-sans text-[11px] leading-none tracking-[0.18em] text-foreground-tertiary"
          >
            {showReasoning ? (
              <>
                <ChevronUp size={11} strokeWidth={2} />
                Hide reasoning
              </>
            ) : (
              <>
                <ChevronDown size={11} strokeWidth={2} />
                Show reasoning
              </>
            )}
          </button>

          <div
            className={cn(
              "overflow-hidden transition-[max-height,opacity] [transition-duration:var(--dur-tab)] [transition-timing-function:var(--ease-out)]",
              showReasoning ? "max-h-60 opacity-100" : "max-h-0 opacity-0",
            )}
          >
            <div className="mt-2 rounded-[var(--r-sm)] bg-[var(--field-bg)] px-3 py-2.5 font-sans text-[11px] leading-[1.65] text-foreground-tertiary">
              {reasoning}
            </div>
          </div>
        </div>
      )}

      {/* ── Action row ───────────────────────────────────────────────────── */}
      <div className="flex flex-wrap items-center gap-2 px-4 py-3">
        {state === "editing" ? (
          // ── Edit mode actions ──────────────────────────────────────────
          <>
            <button
              onClick={handleApplyEdit}
              className="inline-flex cursor-pointer items-center gap-1.5 rounded-[var(--r-sm)] border-0 bg-[image:var(--grad-brand)] px-4 py-[7px] font-sans text-[13px] font-semibold leading-none text-primary-foreground"
            >
              Apply edit
            </button>
            <button
              onClick={handleCancelEdit}
              className="cursor-pointer rounded-[var(--r-sm)] border border-[var(--line-2)] bg-[var(--field-bg)] px-[13px] py-[7px] font-sans text-[13px] leading-none text-foreground-secondary"
            >
              Cancel
            </button>
          </>
        ) : (
          // ── Idle mode actions ──────────────────────────────────────────
          <>
            {/* Primary — accept as-is */}
            <button
              onClick={handleAccept}
              className="inline-flex cursor-pointer items-center gap-1.5 rounded-[var(--r-sm)] border-0 bg-[image:var(--grad-brand)] px-4 py-[7px] font-sans text-[13px] font-semibold leading-none text-primary-foreground transition-[filter] [transition-duration:var(--dur-fast)] [transition-timing-function:var(--ease-out)] hover:brightness-110"
            >
              {/* Checkmark glyph */}
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden>
                <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Use this suggestion
            </button>

            {/* Secondary — discuss in Ask Nova */}
            <button
              onClick={handleDiscussWithNova}
              className="inline-flex cursor-pointer items-center gap-1.5 rounded-[var(--r-sm)] border border-[var(--line-2)] bg-elevated px-[13px] py-[7px] font-sans text-[13px] leading-none text-foreground transition-[background,border-color] [transition-duration:var(--dur-fast)] [transition-timing-function:var(--ease-out)] hover:border-[var(--line-3)] hover:bg-field"
            >
              <MessageSquareText size={13} />
              Discuss with Nova
            </button>
          </>
        )}
      </div>
    </div>
  );
}
