/**
 * NovaBlock — unified AI suggestion component
 *
 * Used across all 8D step screens and the CAPA intake wizard.
 * Wraps one Nova-generated suggestion with confidence indicator,
 * collapsible reasoning, and accept / discuss flow.
 *
 * States: idle → editing → accepted
 */

import { useEffect, useRef, useState } from "react";
import { ChevronDown, ChevronUp, MessageSquareText, Sparkles } from "lucide-react";
import { useAuditTrailStore, useUIStore } from "@/store";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface NovaBlockProps {
  /** The main suggestion text generated by Nova */
  suggestion: string;
  /** Optional chain-of-thought shown in the expandable reasoning panel */
  reasoning?: string;
  /** 0–100 confidence score displayed as a badge — hidden when omitted */
  confidence?: number;
  /** Called when user accepts (as-is or after editing). Receives final text. */
  onAccept?: (content: string) => void;
  /** When true, renders an animated skeleton while Nova is generating */
  loading?: boolean;
  /** Short qualifier appended to the header — e.g. "for Why 1" */
  context?: string;
  /** CAPA ID used for audit trail events */
  capaId?: string;
  /** Unique ID for this suggestion used in audit entries */
  suggestionId?: string;
}

type BlockState = "idle" | "editing" | "accepted";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Clamp confidence to 0–100, format as percentage string */
function formatConfidence(n: number): string {
  return `${Math.max(0, Math.min(100, Math.round(n)))}% confident`;
}

/** Color-tint the confidence badge based on score */
function confidenceColor(n: number): string {
  if (n >= 85) return "var(--success)";
  if (n >= 65) return "var(--warning)";
  return "var(--danger)";
}

// ─────────────────────────────────────────────────────────────────────────────
// Skeleton (loading state)
// ─────────────────────────────────────────────────────────────────────────────

function NovaBlockSkeleton() {
  const shimmer: React.CSSProperties = {
    borderRadius: "var(--r-sm)",
    height: "14px",
    marginBottom: "8px",
  };
  return (
    <div
      style={{
        background: "var(--bg-3)",
        borderTop: "1px solid var(--accent-line)",
        borderRight: "1px solid var(--accent-line)",
        borderBottom: "1px solid var(--accent-line)",
        borderLeft: "3px solid var(--accent)",
        borderRadius: "var(--r-md)",
        padding: "16px",
      }}
    >
      {/* Header placeholder */}
      <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "16px" }}>
        <div
          className="animate-shimmer"
          style={{ ...shimmer, width: "14px", height: "14px", borderRadius: "50%", marginBottom: 0 }}
        />
        <div className="animate-shimmer" style={{ ...shimmer, width: "120px", marginBottom: 0 }} />
        <div
          className="animate-shimmer"
          style={{ ...shimmer, width: "80px", marginBottom: 0, marginLeft: "auto", height: "20px", borderRadius: "20px" }}
        />
      </div>

      {/* Body placeholders */}
      <div className="animate-shimmer" style={{ ...shimmer, width: "100%" }} />
      <div className="animate-shimmer" style={{ ...shimmer, width: "88%" }} />
      <div className="animate-shimmer" style={{ ...shimmer, width: "72%", marginBottom: "16px" }} />

      {/* Action row placeholders */}
      <div style={{ display: "flex", gap: "8px" }}>
        <div className="animate-shimmer" style={{ ...shimmer, width: "130px", height: "30px", marginBottom: 0, borderRadius: "var(--r-sm)" }} />
        <div className="animate-shimmer" style={{ ...shimmer, width: "90px", height: "30px", marginBottom: 0, borderRadius: "var(--r-sm)" }} />
        <div className="animate-shimmer" style={{ ...shimmer, width: "50px", height: "30px", marginBottom: 0, borderRadius: "var(--r-sm)" }} />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────

export function NovaBlock({
  suggestion,
  reasoning,
  confidence,
  onAccept,
  loading = false,
  context,
  capaId,
  suggestionId = "nova-block",
}: NovaBlockProps) {
  const [state, setState] = useState<BlockState>("idle");
  const [draft, setDraft] = useState(suggestion);
  const [showReasoning, setShowReasoning] = useState(false);
  const [isFlashing, setIsFlashing] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const addEvent = useAuditTrailStore((s) => s.addEvent);
  const openNovaChat = useUIStore((s) => s.openNovaChat);

  // Keep draft in sync if suggestion prop changes (e.g. Nova re-generates)
  useEffect(() => {
    if (state === "idle") setDraft(suggestion);
  }, [suggestion, state]);

  // ── Audit helper ───────────────────────────────────────────────────────
  function logAudit(eventType: "nova_suggestion_accepted" | "nova_suggestion_replaced", action: string) {
    if (!capaId) return;
    addEvent({
      actorName: "Nova Demo User",
      actorRole: "CAPA User",
      domain: "ai_decision",
      eventType,
      action,
      capaId,
      novaMetadata: {
        modelName: "Nova Mock Engine",
        modelVersion: "nova-demo-v1",
        confidenceScore: confidence ?? 84,
      },
    });
  }

  // ── Handlers ───────────────────────────────────────────────────────────
  function handleAccept() {
    // Flash the suggestion body before collapsing
    setIsFlashing(true);
    setTimeout(() => {
      setIsFlashing(false);
      setState("accepted");
      onAccept?.(draft);
      logAudit("nova_suggestion_accepted", `Nova suggestion "${suggestionId}" accepted.`);
    }, 380);
  }

  function handleApplyEdit() {
    setState("accepted");
    onAccept?.(draft);
    logAudit("nova_suggestion_accepted", `Nova suggestion "${suggestionId}" accepted after editing.`);
  }

  function handleCancelEdit() {
    setState("idle");
    setDraft(suggestion);
  }

  function handleDiscussWithNova() {
    const label = context ?? "Nova suggestion";
    openNovaChat({
      capaId,
      step: suggestionId,
      source: "nova-suggestion",
      suggestionId,
      suggestionContext: label,
      suggestionText: draft,
      initialDraft: `Help me review this ${label}. What should I ask or improve before using it?`,
    });
    logAudit("nova_suggestion_replaced", `Nova suggestion "${suggestionId}" opened in Ask Nova for discussion.`);
  }

  function handleRestore() {
    setState("idle");
    setDraft(suggestion);
  }

  // ── Loading skeleton ───────────────────────────────────────────────────
  if (loading) return <NovaBlockSkeleton />;

  // ── Accepted ───────────────────────────────────────────────────────────
  if (state === "accepted") {
    return (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
          gap: "8px",
          padding: "9px 14px",
          background: "var(--accent-soft)",
          border: "1px solid var(--accent-line)",
          borderRadius: "var(--r-md)",
          animation: "leadReveal var(--dur-tab) var(--ease-out) both",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "8px", width: "100%" }}>
          <Sparkles
            size={13}
            strokeWidth={1.75}
            style={{ color: "var(--accent)", flexShrink: 0 }}
          />
          <span
            style={{
              fontSize: "13px",
              fontWeight: 600,
              color: "var(--accent)",
              fontFamily: "var(--font-sans)",
            }}
          >
            Nova suggestion applied
          </span>
          <span
            style={{
              fontSize: "12px",
              color: "var(--fg-3)",
              fontFamily: "var(--font-sans)",
            }}
          >
            — edit the field below to refine
          </span>
          <button
            onClick={handleRestore}
            style={{
              marginLeft: "auto",
              fontSize: "12px",
              color: "var(--fg-3)",
              background: "none",
              border: "none",
              cursor: "pointer",
              padding: "2px 6px",
              fontFamily: "var(--font-sans)",
              lineHeight: 1,
            }}
          >
            Undo
          </button>
        </div>
        <p style={{ margin: 0, color: "var(--fg-2)", fontSize: "13px", lineHeight: 1.6, fontFamily: "var(--font-sans)" }}>
          {draft}
        </p>
      </div>
    );
  }

  // ── Idle / Editing ─────────────────────────────────────────────────────
  return (
    <div
      style={{
        background: "var(--bg-3)",
        borderTop: "1px solid var(--accent-line)",
        borderRight: "1px solid var(--accent-line)",
        borderBottom: "1px solid var(--accent-line)",
        borderLeft: "3px solid var(--accent)",
        borderRadius: "var(--r-md)",
        overflow: "hidden",
        // Stagger-reveal when first mounted
        animation: "leadReveal var(--dur-reveal) var(--ease-out) both",
      }}
    >
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "8px",
          padding: "12px 16px 0",
        }}
      >
        <Sparkles
          size={15}
          strokeWidth={1.75}
          style={{ color: "var(--accent)", flexShrink: 0 }}
        />

        <span
          style={{
            fontSize: "13px",
            fontWeight: 600,
            color: "var(--fg-1)",
            fontFamily: "var(--font-sans)",
            lineHeight: 1,
          }}
        >
          Nova's suggestion
          {context && (
            <span
              style={{
                fontWeight: 400,
                color: "var(--fg-3)",
                marginLeft: "6px",
              }}
            >
              {context}
            </span>
          )}
        </span>

        {/* Confidence badge */}
        {confidence !== undefined && (
          <span
            style={{
              marginLeft: "auto",
              display: "inline-flex",
              alignItems: "center",
              gap: "4px",
              padding: "3px 9px",
              borderRadius: "20px",
              background: "var(--accent-soft)",
              border: "1px solid var(--accent-line)",
              fontSize: "11px",
              fontFamily: "var(--font-mono)",
              fontWeight: 600,
              color: confidenceColor(confidence),
              letterSpacing: "0.02em",
              whiteSpace: "nowrap",
            }}
          >
            {formatConfidence(confidence)}
          </span>
        )}
      </div>

      {/* ── Suggestion body ──────────────────────────────────────────────── */}
      <div
        style={{
          padding: "10px 16px 0",
          transition: "background 380ms ease",
          background: isFlashing ? "var(--accent-soft)" : "transparent",
          borderRadius: "4px",
          margin: "0 4px",
        }}
      >
        {state === "editing" ? (
          <textarea
            ref={textareaRef}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            rows={4}
            style={{
              width: "100%",
              background: "var(--field-bg)",
              border: "1px solid var(--accent)",
              borderRadius: "var(--r-sm)",
              padding: "10px 12px",
              fontSize: "14px",
              lineHeight: "1.6",
              color: "var(--fg-1)",
              fontFamily: "var(--font-sans)",
              resize: "vertical",
              outline: "none",
              boxSizing: "border-box",
              boxShadow: "0 0 0 3px var(--accent-soft)",
              display: "block",
            }}
          />
        ) : (
          <p
            style={{
              margin: 0,
              fontSize: "15px",
              lineHeight: "1.6",
              color: "var(--fg-2)",
              fontFamily: "var(--font-sans)",
            }}
          >
            {draft}
          </p>
        )}
      </div>

      {/* ── Expandable reasoning ─────────────────────────────────────────── */}
      {reasoning && state !== "editing" && (
        <div style={{ padding: "8px 16px 0" }}>
          <button
            onClick={() => setShowReasoning((v) => !v)}
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "4px",
              background: "none",
              border: "none",
              padding: 0,
              cursor: "pointer",
              fontSize: "11px",
              fontFamily: "var(--font-mono)",
              color: "var(--fg-3)",
              letterSpacing: "0.18em",
              lineHeight: 1,
            }}
          >
            {showReasoning ? (
              <>
                <ChevronUp size={11} strokeWidth={2} />
                Hide reasoning
              </>
            ) : (
              <>
                <ChevronDown size={11} strokeWidth={2} />
                Show reasoning
              </>
            )}
          </button>

          <div
            style={{
              overflow: "hidden",
              maxHeight: showReasoning ? "240px" : "0",
              opacity: showReasoning ? 1 : 0,
              transition: "max-height var(--dur-tab) var(--ease-out), opacity var(--dur-tab) var(--ease-out)",
            }}
          >
            <div
              style={{
                marginTop: "8px",
                padding: "10px 12px",
                background: "var(--field-bg)",
                borderRadius: "var(--r-sm)",
                fontFamily: "var(--font-mono)",
                fontSize: "11px",
                lineHeight: "1.65",
                color: "var(--fg-3)",
              }}
            >
              {reasoning}
            </div>
          </div>
        </div>
      )}

      {/* ── Action row ───────────────────────────────────────────────────── */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "8px",
          padding: "12px 16px",
          flexWrap: "wrap",
        }}
      >
        {state === "editing" ? (
          // ── Edit mode actions ──────────────────────────────────────────
          <>
            <button
              onClick={handleApplyEdit}
              style={{
                background: "var(--grad-brand)",
                color: "var(--on-accent)",
                border: "none",
                borderRadius: "var(--r-sm)",
                padding: "7px 16px",
                fontSize: "13px",
                fontWeight: 600,
                cursor: "pointer",
                fontFamily: "var(--font-sans)",
                lineHeight: 1,
                display: "inline-flex",
                alignItems: "center",
                gap: "6px",
              }}
            >
              Apply edit
            </button>
            <button
              onClick={handleCancelEdit}
              style={{
                background: "var(--field-bg)",
                color: "var(--fg-2)",
                border: "1px solid var(--line-2)",
                borderRadius: "var(--r-sm)",
                padding: "7px 13px",
                fontSize: "13px",
                cursor: "pointer",
                fontFamily: "var(--font-sans)",
                lineHeight: 1,
              }}
            >
              Cancel
            </button>
          </>
        ) : (
          // ── Idle mode actions ──────────────────────────────────────────
          <>
            {/* Primary — accept as-is */}
            <button
              onClick={handleAccept}
              style={{
                background: "var(--grad-brand)",
                color: "var(--on-accent)",
                border: "none",
                borderRadius: "var(--r-sm)",
                padding: "7px 16px",
                fontSize: "13px",
                fontWeight: 600,
                cursor: "pointer",
                fontFamily: "var(--font-sans)",
                lineHeight: 1,
                display: "inline-flex",
                alignItems: "center",
                gap: "6px",
                transition: "filter var(--dur-fast) var(--ease-out)",
              }}
              onMouseEnter={(e) => ((e.currentTarget as HTMLButtonElement).style.filter = "brightness(1.1)")}
              onMouseLeave={(e) => ((e.currentTarget as HTMLButtonElement).style.filter = "none")}
            >
              {/* Checkmark glyph */}
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden>
                <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Use this suggestion
            </button>

            {/* Secondary — discuss in Ask Nova */}
            <button
              onClick={handleDiscussWithNova}
              style={{
                background: "var(--bg-3)",
                color: "var(--fg-1)",
                border: "1px solid var(--line-2)",
                borderRadius: "var(--r-sm)",
                padding: "7px 13px",
                fontSize: "13px",
                cursor: "pointer",
                fontFamily: "var(--font-sans)",
                lineHeight: 1,
                display: "inline-flex",
                alignItems: "center",
                gap: "6px",
                transition: "border-color var(--dur-fast) var(--ease-out), background var(--dur-fast) var(--ease-out)",
              }}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--line-3)";
                (e.currentTarget as HTMLButtonElement).style.background = "var(--bg-4)";
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.borderColor = "var(--line-2)";
                (e.currentTarget as HTMLButtonElement).style.background = "var(--bg-3)";
              }}
            >
              <MessageSquareText size={13} />
              Discuss with Nova
            </button>
          </>
        )}
      </div>
    </div>
  );
}
